import { promises as fs } from "node:fs";
import path from "node:path";
import {
  retroActionItemsRepository,
  retroCardsRepository,
  retrosRepository,
  settingsRepository,
  sprintsRepository,
  storiesRepository,
  teamMemberLinksRepository,
  teamMembersRepository,
  teamsRepository
} from "../repositories";

async function clearDataDir() {
  const cwd = process.cwd();
  const dataDir = cwd.endsWith(`${path.sep}server`)
    ? path.join(cwd, "data")
    : path.join(cwd, "server", "data");
  await fs.mkdir(dataDir, { recursive: true });
  const entries = await fs.readdir(dataDir);
  await Promise.all(entries.map((name) => fs.rm(path.join(dataDir, name), { force: true })));
}

async function main() {
  await clearDataDir();

  const engineering = await teamsRepository.create({
    name: "Engineering",
    description: "Top-level engineering function",
    parentTeamId: null,
    color: "var(--color-team-1)"
  });
  const platform = await teamsRepository.create({
    name: "Platform",
    description: "Shared services and foundations",
    parentTeamId: engineering.id,
    color: "var(--color-team-2)"
  });
  const product = await teamsRepository.create({
    name: "Product",
    description: "Feature delivery teams",
    parentTeamId: engineering.id,
    color: "var(--color-team-3)"
  });
  const infra = await teamsRepository.create({
    name: "Infrastructure",
    description: "Cloud and reliability",
    parentTeamId: platform.id,
    color: "var(--color-team-4)"
  });
  const mobile = await teamsRepository.create({
    name: "Mobile",
    description: "iOS and Android experience",
    parentTeamId: product.id,
    color: "var(--color-team-5)"
  });
  const cloudOps = await teamsRepository.create({
    name: "Cloud Ops",
    description: "Runtime operations and cloud governance",
    parentTeamId: infra.id,
    color: "var(--color-team-6)"
  });

  const members = await Promise.all([
    teamMembersRepository.create({
      name: "Avery Kim",
      roleType: "scrum_master",
      avatar: { color: "var(--color-avatar-1)", initials: "AK" },
      defaultAvailabilityDays: 8,
      capacityMultiplier: 100,
      isActive: true
    }),
    teamMembersRepository.create({
      name: "Morgan Lee",
      roleType: "product_owner",
      avatar: { color: "var(--color-avatar-2)", initials: "ML" },
      defaultAvailabilityDays: 8,
      capacityMultiplier: 100,
      isActive: true
    }),
    teamMembersRepository.create({
      name: "Jordan Patel",
      roleType: "team_member",
      avatar: { color: "var(--color-avatar-3)", initials: "JP" },
      defaultAvailabilityDays: 8,
      capacityMultiplier: 50,
      isActive: true
    }),
    teamMembersRepository.create({
      name: "Riley Chen",
      roleType: "coordinator",
      coordinatorTitle: "SoSM",
      coordinatorTeamIds: [platform.id, product.id],
      avatar: { color: "var(--color-avatar-4)", initials: "RC" },
      defaultAvailabilityDays: 8,
      capacityMultiplier: 100,
      isActive: true
    }),
    teamMembersRepository.create({
      name: "Parker Diaz",
      roleType: "coordinator",
      coordinatorTitle: "SoSoSM",
      coordinatorTeamIds: [engineering.id],
      avatar: { color: "var(--color-avatar-5)", initials: "PD" },
      defaultAvailabilityDays: 8,
      capacityMultiplier: 100,
      isActive: true
    })
  ]);

  const [avery, morgan, jordan, riley, parker] = members;

  await Promise.all([
    teamMemberLinksRepository.create({ teamId: engineering.id, memberId: parker.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: platform.id, memberId: avery.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: product.id, memberId: morgan.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: infra.id, memberId: jordan.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: cloudOps.id, memberId: jordan.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: mobile.id, memberId: jordan.id, joinedAt: new Date().toISOString() }),
    teamMemberLinksRepository.create({ teamId: engineering.id, memberId: riley.id, joinedAt: new Date().toISOString() })
  ]);

  await settingsRepository.getOrCreateDefault();

  // Minimal sprint/story data for local demo continuity.
  const sprint = await sprintsRepository.create({
    name: "Sprint Seed",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    goal: "Seed sprint",
    status: "active"
  });
  await storiesRepository.create({
    sprintId: sprint.id,
    title: "Seed Story",
    description: "Generated by seed script",
    storyPoints: 3,
    assigneeMemberId: jordan.id,
    labels: ["seed"],
    acceptanceCriteria: ["Runs locally"],
    boardColumn: "backlog"
  });

  // Keep repository files warm.
  await Promise.all([
    retrosRepository.getAll(),
    retroCardsRepository.getAll(),
    retroActionItemsRepository.getAll()
  ]);

  // eslint-disable-next-line no-console
  console.log("Seed complete: teams, members, hierarchy, coordinators, and sample sprint data created.");
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});

